/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      colors: {
        outline: '#8e9378',
        'outline-variant': '#444933',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'surface-tint': '#aed500',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c5c9ac',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        background: '#131313',
        'on-background': '#e5e2e1',
        primary: '#ffffff',
        'on-primary': '#293500',
        'primary-container': '#c7f300',
        'on-primary-container': '#576c00',
        'inverse-primary': '#526600',
        'primary-fixed': '#c7f300',
        'primary-fixed-dim': '#aed500',
        'on-primary-fixed': '#171e00',
        'on-primary-fixed-variant': '#3d4d00',
        secondary: '#d3fbff',
        'on-secondary': '#00363a',
        'secondary-container': '#00eefc',
        'on-secondary-container': '#00686f',
        'secondary-fixed': '#7df4ff',
        'secondary-fixed-dim': '#00dbe9',
        'on-secondary-fixed': '#002022',
        'on-secondary-fixed-variant': '#004f54',
        tertiary: '#ffffff',
        'on-tertiary': '#1c333e',
        'tertiary-container': '#cde6f4',
        'on-tertiary-container': '#506873',
        'tertiary-fixed': '#cde6f4',
        'tertiary-fixed-dim': '#b2cad8',
        'on-tertiary-fixed': '#051e28',
        'on-tertiary-fixed-variant': '#334a55',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'max-width': '1280px',
      },
      animation: {
        scanline: 'scanline 6s linear infinite',
        flickerNeon: 'flickerNeon 3s infinite',
        blink: 'blink 1s step-end infinite',
      },
      keyframes: {
        scanline: {
          '0%': { top: '0%' },
          '100%': { top: '100%' },
        },
        flickerNeon: {
          '0%, 19.999%, 22%, 62.999%, 64%, 64.999%, 70%, 100%': { opacity: '1' },
          '20%, 21.999%, 63%, 63.999%, 65%, 69.999%': { opacity: '0.4' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
      },
    },
  },
  plugins: [],
};
